[package]
name = "aeco-patch-configurator-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rfd = "0.10.0"
aeco-patch-config = { path = "../aeco-patch-config/" }

